In [62]:
import keras
import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Setting seed for reproducability
np.random.seed(1234)  
PYTHONHASHSEED = 0
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, recall_score, precision_score
from keras import models
from keras.wrappers.scikit_learn import KerasRegressor
from keras.models import Sequential,model_from_json
from keras.layers import Dense, Dropout, LSTM, Activation
%matplotlib inline
from decimal import Decimal
import warnings
warnings.filterwarnings("ignore")
import pickle
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,Normalizer, MinMaxScaler
from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import GridSearchCV
from numpy.random import seed
seed(1)
from tensorflow import set_random_seed
set_random_seed(2)
from sklearn.metrics import mean_absolute_error
from sklearn import ensemble
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
import xgboost as xgb

import pickle
from sklearn.externals import joblib
import os
import re

In [131]:
#!/bin/python3

import numpy as np
import os
import sys

def generate_data():
    np.random.seed(111)
    nsamples = 10000
    x = [np.random.uniform(low=-100.0, high=0.0, size=nsamples),
         np.random.choice(['yes', 'no'], size=nsamples),
         np.random.beta(a=2.0, b=4.5, size=nsamples),
         np.random.exponential(scale=1.0, size=nsamples),
         np.random.choice([1, 2, 3, 4, 5], size=nsamples)]
    probabilities = np.linspace(0, 1, num=nsamples)
    y = np.random.binomial(1, probabilities, size=nsamples)
    for i, xi in enumerate(x):
        xy = np.column_stack((np.sort(xi), y))
        np.random.shuffle(xy)
        xy = xy[xy[:, 1].argsort()]
        x[i] = xy[:, 0]
    y = np.sort(y)

    return x, y

# Define any functions you need here.
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_score

def pre_process(x):
    #
    # Write your code here.
    #
    
    X=np.array([(x[0]-np.min(x[0]))/(np.max(x[0])-np.min(x[0])),
     np.where(x[1]=='yes',1,0),
     x[2],
     x[3],
     x[4],
    ])
    
    
#     X = np.zeros((10000,5))  # TODO replace with real computation    
    
    return np.transpose(X)

def compute_accuracy(X,y):
    #
    # Write your code here.
    # 

    k=10
    feature_accuracies = np.zeros(5) # TODO replace with real computation
    
    for i in range(X.shape[1]):
        model = LogisticRegression()
        feature_accuracies[i] = cross_val_score(model,X[:,i][:,np.newaxis],y,cv=k, scoring ='mean_absolute_error').mean()
    
    joint_model = LogisticRegression()
    joint_accuracy = cross_val_score(
            joint_model, X, y,cv=k, scoring ='mean_absolute_error'
        ).mean()    
    
    return feature_accuracies, joint_accuracy
    
if __name__ == '__main__':
    x, y = generate_data()

    X = pre_process(x)
    print(X.shape)
    
    print("Pre-processed means: {}".format(X.mean(axis=0)))
    print("Pre-processed std: {}".format(X.std(axis=0)))
 
    feature_accuracies, joint_accuracy = compute_accuracy(X,y)
    print("Feature Accuracies = {}".format(feature_accuracies))

    print("Joint Accuracy = {}".format(joint_accuracy))
    
pd.DataFrame(np.transpose(X))

(10000, 5)
Pre-processed means: [0.503723   0.5012     0.30324468 0.99428285 2.9961    ]
Pre-processed std: [0.28858856 0.49999856 0.16609502 0.9984393  1.41353627]
Feature Accuracies = [-0.244  -0.2436 -0.2448 -0.2512 -0.2526]
Joint Accuracy = -0.07559999999999999

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,0.222652,0.115985,0.453375,0.009968,0.559691,0.600493,0.067632,0.344662,0.356045,0.176588,...,0.597486,0.888427,0.606082,0.555967,0.262928,0.877263,0.685407,0.410491,0.545503,0.665170
1,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000
2,0.062524,0.141467,0.171497,0.233134,0.369984,0.071010,0.345022,0.148838,0.236505,0.042473,...,0.247608,0.191090,0.075812,0.310577,0.333327,0.364919,0.325506,0.816650,0.238111,0.443478
3,0.167274,0.386761,1.440839,0.154594,0.628675,0.519336,0.211842,0.079846,0.170592,0.603716,...,1.172321,1.426725,0.530199,1.912439,2.847732,0.884273,1.089432,1.829590,2.700886,0.390011
4,2.000000,2.000000,4.000000,1.000000,1.000000,3.000000,3.000000,1.000000,4.000000,2.000000,...,3.000000,2.000000,4.000000,4.000000,5.000000,3.000000,3.000000,3.000000,5.000000,5.000000

In [104]:
log_records = pd.read_csv("test.txt", sep=r'\s(?=(?:[^"]*"[^"]*")*[^"]*$)(?![^\[]*\])', header=None)
num_requests = log_records.groupby([0])[0].agg(['count'])
num_requests.to_csv("test1.txt", header=None, sep=r" ")

In [4]:
# df=pd.read_csv('C:\\Users\\lengada1\\NCSU\\ten_skus.csv')
df=pd.read_csv('./ten_skus.csv')
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.weekday_name

day_dummy=pd.get_dummies(df.Day)
df=pd.concat([df,day_dummy],axis=1)
df.drop(['Day','Date'],inplace=True,axis=1)

In [5]:
def split_df(df):
    d={}
    split_by_list=np.unique(df.id.values)
    for sku in split_by_list:
        d[sku]=df[df.id==sku]
    return d

df_dict=split_df(df);

In [6]:
y={}
for sku in list(df_dict.keys()):
    y[sku]=df_dict[sku]['Sales']

In [7]:
X={}
X_raw={}
for sku in list(df_dict.keys()):
    X_raw[sku]=df_dict[sku]
    X_raw[sku]=X_raw[sku].drop(['id','DayOfWeek','High_Var',"Luxury",'Customers','Sales'],axis=1)

In [8]:
for sku in list(df_dict.keys()):
    for obs in range(1,8):
        X_raw[sku]["Sales_T"+str(obs)]=df_dict[sku]['Sales'].shift(obs)

In [9]:
for sku in list(df_dict.keys()):
    X_raw[sku]["Mov_avg"]=df_dict[sku]['Sales'].rolling( window=7).mean().shift(1)

In [10]:
len(df)

9420

In [11]:
#Cut lagged vars NAs off top 
cut_lag=7;
for sku in list(df_dict.keys()):
    y[sku]=y[sku][cut_lag:]
    y[sku].reset_index(drop=True, inplace=True)
    
for sku in list(df_dict.keys()):
    X[sku]=X_raw[sku][cut_lag:]
    X[sku].reset_index(drop=True, inplace=True)

In [12]:
X[1].head()

,Open,Promo,SchoolHoliday,Year,Month,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,Sales_T1,Sales_T2,Sales_T3,Sales_T4,Sales_T5,Sales_T6,Sales_T7,Mov_avg
0,1,1,1,2013,1,0,0,0,0,0,1,0,7176.0,0.0,4997.0,4486.0,4327.0,5530.0,0.0,3788.000000
1,1,1,1,2013,1,0,0,0,0,0,0,1,5580.0,7176.0,0.0,4997.0,4486.0,4327.0,5530.0,4585.142857
2,1,1,1,2013,1,0,0,0,0,1,0,0,5471.0,5580.0,7176.0,0.0,4997.0,4486.0,4327.0,4576.714286
3,1,1,1,2013,1,1,0,0,0,0,0,0,4892.0,5471.0,5580.0,7176.0,0.0,4997.0,4486.0,4657.428571
4,1,0,0,2013,1,0,0,1,0,0,0,0,4881.0,4892.0,5471.0,5580.0,7176.0,0.0,4997.0,4713.857143

In [46]:
# Create skus_t1.csv
skus_t1 = pd.DataFrame({
    1:X[1]["Sales_T1"], 2:X[2]["Sales_T1"],
    3:X[3]["Sales_T1"], 4:X[4]["Sales_T1"],
    5:X[5]["Sales_T1"], 6:X[6]["Sales_T1"],
    7:X[7]["Sales_T1"], 8:X[8]["Sales_T1"],
    9:X[9]["Sales_T1"], 10:X[10]["Sales_T1"],
})
skus_t1.to_csv("skus_t1.csv")
skus_t1

,1,2,3,4,5,6,7,8,9,10
0,7176.0,6775.0,12247.0,12112.0,6978.0,8591.0,12718.0,7416.0,7574.0,7804.0
1,5580.0,6318.0,9800.0,10031.0,5718.0,7099.0,10073.0,6333.0,6206.0,5394.0
2,5471.0,6763.0,8001.0,8857.0,5974.0,6749.0,7049.0,5038.0,4699.0,5696.0
3,4892.0,5618.0,7772.0,9472.0,4999.0,6282.0,8234.0,6084.0,5340.0,5419.0
4,4881.0,4810.0,9292.0,10512.0,5159.0,6829.0,7115.0,4997.0,5855.0,5556.0
5,4952.0,2630.0,4455.0,9719.0,1760.0,3829.0,4236.0,2660.0,4657.0,4402.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,4717.0,3995.0,4566.0,7794.0,4045.0,5908.0,6385.0,4128.0,4761.0,4685.0
8,3900.0,4075.0,5041.0,7121.0,3916.0,5861.0,6780.0,4358.0,2724.0,4470.0
9,4008.0,4198.0,4827.0,6537.0,3546.0,4454.0,5921.0,3508.0,3761.0,4640.0
10,4044.0,2973.0,4463.0,7088.0,3401.0,5235.0,6779.0,4833.0,3702.0,4460.0
11,4127.0,3441.0,5390.0,7857.0,4227.0,5553.0,7010.0,3619.0,5325.0,4962.0
12,5182.0,2399.0,3938.0,9455.0,1698.0,3702.0,4451.0,2357.0,4883.0,4441.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,5394.0,6311.0,6014.0,11667.0,6217.0,6764.0,10832.0,7589.0,4658.0,6178.0
15,5720.0,5803.0,7961.0,9977.0,5680.0,7066.0,9074.0,5893.0,6065.0,5215.0
16,5578.0,5974.0,7863.0,9236.0,6110.0,7343.0,7664.0,6469.0,4904.0,5218.0
17,5195.0,5091.0,7910.0,8516.0,4397.0,5844.0,7690.0,6114.0,5237.0,4736.0
18,5586.0,4589.0,7565.0,9730.0,4960.0,6433.0,8360.0,5251.0,5501.0,5404.0
19,5598.0,2205.0,3902.0,9323.0,1570.0,3443.0,3774.0,2366.0,4544.0,4789.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,4055.0,3549.0,5352.0,7374.0,3089.0,6209.0,6483.0,3459.0,4683.0,4489.0
22,3725.0,3461.0,5375.0,7559.0,3569.0,5411.0,6480.0,3846.0,3941.0,4374.0
23,4601.0,4446.0,4920.0,7601.0,4273.0,5751.0,5401.0,3638.0,4341.0,3986.0
24,4709.0,4340.0,5682.0,10359.0,4392.0,6458.0,7072.0,5680.0,5098.0,4867.0
25,5633.0,4545.0,6725.0,9332.0,4241.0,6601.0,8721.0,4406.0,5610.0,4470.0
26,5970.0,2956.0,5155.0,11123.0,1757.0,3927.0,5752.0,2399.0,5862.0,4357.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,7032.0,6480.0,10913.0,13937.0,6846.0,7954.0,11182.0,8273.0,7431.0,7617.0
29,6049.0,6269.0,9372.0,11353.0,5662.0,7334.0,9502.0,6901.0,6691.0,5423.0
...,...,...,...,...,...,...,...,...,...,...
905,5223.0,6431.0,8311.0,11216.0,6253.0,5804.0,11024.0,8523.0,8490.0,7896.0
906,5558.0,6189.0,7450.0,10323.0,6035.0,5335.0,10996.0,8658.0,8395.0,6317.0
907,4665.0,4838.0,8149.0,11543.0,4475.0,4594.0,11976.0,6535.0,8363.0,5915.0
908,4797.0,4475.0,4482.0,9358.0,2240.0,2979.0,6559.0,3418.0,6223.0,5120.0
909,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
910,4359.0,4132.0,6736.0,9967.0,4328.0,4508.0,10790.0,6740.0,7758.0,6143.0
911,3650.0,4313.0,6180.0,8127.0,4036.0,4021.0,9207.0,5365.0,6940.0,5476.0
912,3797.0,5676.0,6347.0,8620.0,4990.0,4072.0,9204.0,5322.0,5621.0,4865.0
913,3897.0,4082.0,6613.0,9093.0,4601.0,4095.0,9608.0,5602.0,6285.0,4871.0
914,3808.0,4384.0,6316.0,9177.0,4252.0,4530.0,9499.0,6067.0,6007.0,5747.0
915,3530.0,2677.0,4011.0,10996.0,2023.0,3134.0,6425.0,3707.0,5076.0,4636.0
916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
917,5054.0,6874.0,9462.0,13550.0,7425.0,6827.0,13250.0,9117.0,10399.0,6757.0
918,5042.0,6122.0,8625.0,12315.0,6144.0,5758.0,12294.0,8845.0,7841.0,7491.0
919,4767.0,6406.0,8663.0,11126.0,6323.0,4582.0,10095.0,7932.0,7013.0,6423.0
920,4427.0,5062.0,7909.0,11432.0,4963.0,5115.0,10774.0,8808.0,8113.0,6275.0
921,4852.0,4518.0,6679.0,10514.0,4355.0,4422.0,10339.0,6728.0,6845.0,5356.0
922,4406.0,3417.0,4258.0,9703.0,2108.0,2915.0,6861.0,3813.0,5987.0,5761.0
923,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
924,4395.0,4435.0,5798.0,10283.0,4183.0,4301.0,10159.0,5956.0,7152.0,6111.0
925,3558.0,3836.0,5600.0,9176.0,3497.0,3720.0,9169.0,5168.0,5873.0,6479.0
926,3464.0,5093.0,5414.0,8503.0,3595.0,3469.0,8214.0,4996.0,5649.0,5561.0
927,3769.0,4108.0,5702.0,7286.0,3713.0,3482.0,9550.0,6109.0,6471.0,6401.0
928,3706.0,3854.0,5080.0,8322.0,3815.0,3804.0,9203.0,4917.0,5464.0,6152.0
929,4364.0,2512.0,3878.0,9322.0,2030.0,2892.0,6574.0,3288.0,5330.0,4713.0
930,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
931,6102.0,6627.0,8107.0,11812.0,7059.0,5723.0,14869.0,8739.0,10649.0,7212.0
932,5011.0,5671.0,8864.0,10275.0,6083.0,4839.0,12342.0,6717.0,8751.0,6140.0
933,4782.0,6402.0,7610.0,10514.0,5899.0,5275.0,12074.0,7029.0,7776.0,5524.0
934,5020.0,5567.0,8977.0,10387.0,4943.0,4790.0,11560.0,8420.0,7539.0,6186.0

In [11]:
std={}
for sku in list(df_dict.keys()):
    std[sku] = preprocessing.StandardScaler().fit(X[sku])
    X[sku] = std[sku].transform(X[sku])

In [12]:
cv=4
RF=RandomForestRegressor( n_estimators=1000,max_depth=13,max_features=14, criterion="mae");
rf_models=[];
for sku in list(df_dict.keys()):
    rf_models.append(cross_val_score(RF,X[sku],y[sku],cv=cv, scoring ='mean_absolute_error').mean().round(0) )

In [13]:
GB=ensemble.GradientBoostingRegressor(n_estimators= 200,max_depth=4 , max_features=16,loss='lad');
gb_models=[];
for sku in list(df_dict.keys()):
    gb_models.append(cross_val_score(GB,X[sku],y[sku],cv=cv, scoring ='mean_absolute_error').mean().round(0)  )

In [14]:
XG=xgb.XGBRegressor(n_estimators= 100, max_depth=5,gamma=0  )
xg_models=[]
for sku in list(df_dict.keys()):
    xg_models.append(cross_val_score(XG,X[sku],y[sku],cv=cv, scoring ='mean_absolute_error').mean().round(0)  )

In [15]:
def create_MLP():
    mlp=models.Sequential()
    mlp.add(Dense(20, input_dim=X[1].shape[1], activation='relu'))
    mlp.add(Dense(30, activation='relu'))
    #mlp.add(Dense(30, activation='relu'))
    mlp.add(Dense(10, activation='relu'))
    mlp.add(Dense(1))
    mlp.compile(loss='mae', optimizer='adam', metrics=['mae'])
    return mlp

MLP = KerasRegressor(build_fn=create_MLP,
                               epochs=700,
                               batch_size=25,
                               verbose=0)

In [16]:
mlp_models=[]
for sku in list(df_dict.keys()):
    mlp_models.append(cross_val_score(MLP,X[sku],y[sku],cv=cv).mean().round(0)  )

In [17]:
mae=-pd.DataFrame(np.column_stack((mlp_models,rf_models,gb_models,xg_models)) )
mae=mae.rename(columns = {0:'MLP',1:'RF',2:'GB',3:'XG'})
best=mae.idxmin(axis=1)
best.astype('category')
mae["Best"]=best
mae.index = mae.index + 1
mae.loc['mean'] = mae.mean()
mae['range']=mae.max(axis=1)-mae.min(axis=1)
mae

        MLP     RF     GB     XG Best  range
1     378.0  338.0  360.0  350.0   RF   40.0
2     403.0  378.0  405.0  384.0   RF   27.0
3     613.0  556.0  583.0  571.0   RF   57.0
4     701.0  679.0  687.0  728.0   RF   49.0
5     359.0  355.0  384.0  366.0   RF   29.0
6     475.0  402.0  429.0  406.0   RF   73.0
7     687.0  680.0  714.0  707.0   RF   34.0
8     460.0  432.0  493.0  449.0   RF   61.0
9     580.0  558.0  552.0  562.0   GB   28.0
10    379.0  363.0  369.0  379.0   RF   16.0
mean  503.5  474.1  497.6  490.2  NaN   29.4

In [18]:
#Need lots of rank and counts of how many times models came in 1st  vs 2nd.
def rank_model(df,rank):
    coln = 'Best' + str(rank) 
    sortID = np.argpartition(df[['MLP','RF','GB','XG']].values,rank,axis=1)[:,rank]
    df[coln] = df.columns[sortID]

In [19]:
rank_model(mae,0)
rank_model(mae,1)
mae

        MLP     RF     GB     XG Best  range Best0 Best1
1     378.0  338.0  360.0  350.0   RF   40.0    RF    XG
2     403.0  378.0  405.0  384.0   RF   27.0    RF    XG
3     613.0  556.0  583.0  571.0   RF   57.0    RF    XG
4     701.0  679.0  687.0  728.0   RF   49.0    RF    GB
5     359.0  355.0  384.0  366.0   RF   29.0    RF   MLP
6     475.0  402.0  429.0  406.0   RF   73.0    RF    XG
7     687.0  680.0  714.0  707.0   RF   34.0    RF   MLP
8     460.0  432.0  493.0  449.0   RF   61.0    RF    XG
9     580.0  558.0  552.0  562.0   GB   28.0    GB    RF
10    379.0  363.0  369.0  379.0   RF   16.0    RF    GB
mean  503.5  474.1  497.6  490.2  NaN   29.4    RF    XG

In [20]:
def RF_final(X, y):
    """
    Returns final predictions and final fitted version of RF
    """
    tree=RF
    tree.fit(X,y)
    pred=tree.predict(X)
    pred=pd.DataFrame(pred)
    pred.reset_index(drop=True, inplace=True)
    pred=pred.rename(columns = {0:'RF'})
    return (pred, tree)

def MLP_final(X,y):
    model = MLP
    model.fit(X,y)
    pred=model.predict(X)
    pred=pd.DataFrame(pred)
    pred.reset_index(drop=True, inplace=True)
    pred=pred.rename(columns = {0:'MLP'})
    return (pred, model)

def GB_final(X,y):
    model = GB
    model.fit(X,y)
    prediction=model.predict(X)
    pred=pd.DataFrame(prediction)
    pred.reset_index(drop=True, inplace=True)
    pred=pred.rename(columns = {0:'GB'})
    return (pred, model)

def XG_final(X,y):
    model=XG
    model.fit(X,y)
    prediction=model.predict(X)
    pred=pd.DataFrame(prediction)
    pred.reset_index(drop=True, inplace=True)
    pred=pred.rename(columns = {0:'XG'})
    return (pred, model)

In [21]:
#NOTE, because we are retraining models here, a bad initiatlization could lead to different results. 

def best_model(scores,X,y):
    d={}
    for sku in list(df_dict.keys()):
        
        if scores.loc[sku]["Best"]=="RF":     
            d[sku]=RF_final(X[sku],y[sku])
                    
        elif scores.loc[sku]["Best"]=="MLP":
            d[sku]=MLP_final(X[sku],y[sku])                 
            
        elif scores.loc[sku]["Best"]=="GB":
            d[sku]=GB_final(X[sku],y[sku])
            
        elif scores.loc[sku]["Best"]=="XG":
            d[sku]=XG_final(X[sku],y[sku])
      
    return d

In [22]:
bm_dict=best_model(mae,X,y)
# bm_dict

In [23]:
#MAE of Best Model forecasting over all 935 days.  NN do very poorly here!
mae2=[]
for sku in list(df_dict.keys()):
    mae2.append( mean_absolute_error(y[sku], bm_dict[sku][0])   )
mae2=pd.DataFrame(mae2)
mae2.index = mae2.index + 1
mae2.round(1)

        0
1   150.7
2   180.7
3   247.1
4   288.4
5   157.1
6   156.6
7   285.4
8   165.2
9   311.6
10  163.2

In [24]:
sku_pred=pd.concat([ bm_dict[1][0],bm_dict[2][0],bm_dict[3][0],bm_dict[4][0],bm_dict[5][0],bm_dict[6][0],bm_dict[7][0],bm_dict[8][0],bm_dict[9][0],bm_dict[10][0],
],axis=1) 
sku_pred['Total'] = sku_pred.sum(axis=1)
sku_pred.columns = ['1','2','3','4','5','6','7','8','9','10','Total']
# sku_pred.to_csv('C:\\Users\\lengada1\\NCSU\\prediction_skus.csv')
sku_pred.to_csv('./prediction_skus.csv')

#Each column in this dataframe is the result of 1 of the 4 models
sku_pred

,1,2,3,4,5,6,7,8,9,10,Total
0,5668.7610,6283.6345,9952.9935,10117.8915,5579.7605,7128.6680,10197.9855,6464.1725,6199.253214,5807.9900,73401.110214
1,5432.8880,6513.5385,8458.8885,9169.1855,5819.8900,6876.8355,7767.8200,5529.9350,5208.528819,5618.7430,66396.252819
2,5065.8695,5503.1390,7739.0300,9338.7040,4943.3175,6273.7590,8067.7155,6172.5265,5328.458825,5600.3540,64032.873825
3,4858.0225,4808.1605,8785.7315,10047.5245,5061.9280,6853.7750,8047.0870,5169.0145,5837.535106,5697.7960,65166.574606
4,4892.0730,2569.2615,4429.8755,9826.1225,1813.2975,3800.3570,4437.9550,2550.7345,5088.404565,4486.4490,43894.530065
5,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000004,0.0000,0.000004
6,4494.4940,3980.5235,4952.7665,7778.2045,3960.6950,5945.7855,6640.0030,4210.7980,4927.785194,4756.8760,51647.931194
7,4033.1695,3969.9420,5095.6105,7230.4845,3748.5375,5631.6225,6717.4100,4248.1815,4595.029309,4525.4495,49795.436809
8,3996.3670,4511.3340,5027.8465,6961.7935,3951.7260,5156.9805,6153.4365,3751.1120,4056.198953,4548.8340,48115.628953
9,3945.2320,3787.8060,4798.9560,7248.7625,3582.7540,5444.0990,6767.0770,4829.7625,4646.620365,4475.1585,49526.227865
10,4174.8215,3665.2390,5625.9455,7828.7680,4057.8270,5614.8205,7516.9995,3877.7510,5220.512868,4807.8280,52390.512868
11,5058.0700,2446.5050,4168.2755,9458.7670,1768.2230,3676.1960,4790.4665,2388.2800,4796.771027,4472.3195,43023.873527
12,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-0.009874,0.0000,-0.009874
13,5687.7620,6530.6855,7502.3180,11440.1760,6652.5540,7245.6485,10715.5990,7745.5105,6005.957996,6662.6455,76188.856996
14,5338.4900,5906.2655,8077.9315,9853.3570,5660.5160,6974.4140,9220.7370,6220.2990,6060.299274,5359.0485,68671.357774
15,5430.3530,6164.9380,8336.8565,9308.1350,5898.3040,7109.2680,7879.4825,6041.2745,5025.830904,5224.8565,66419.298904
16,5151.9280,5108.4090,7736.9335,9066.0190,4748.7330,6110.6580,7793.2610,6353.3950,5227.333545,4921.9985,62218.668545
17,5357.5665,4662.4740,7591.1920,9569.5270,4942.6545,6489.3595,8413.0075,5200.1430,5618.153076,5388.7915,63232.868576
18,5453.4390,2392.0605,4028.1775,9613.5245,1691.0675,3562.6840,4260.9805,2395.0080,4734.630969,4629.7225,42761.294969
19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000004,0.0000,0.000004
20,4195.5535,3867.7970,5419.2155,7787.1865,3506.0465,5944.5725,6674.4025,3881.1675,4742.033586,4674.2860,50692.261086
21,3851.4300,3764.5840,5182.7155,7419.6510,3569.9940,5537.5660,6523.1015,3986.8600,4607.486947,4493.9575,48937.346447
22,4318.0010,4450.7690,5080.1805,7552.6515,3986.8995,5675.4670,5824.8635,3779.6085,4229.961364,4307.5365,49205.938364
23,4595.5335,4079.7290,5467.4125,9142.8155,4127.2900,6005.8475,6906.3495,5217.2265,4768.578705,4595.5555,54906.338205
24,5358.6760,4399.3820,6406.3560,9491.6425,4243.9795,6375.9010,8568.0315,4318.1495,5045.106175,4648.1305,58855.354675
25,5804.4530,2893.6240,4774.0085,10773.0715,1807.2540,3928.2370,5719.4810,2451.8160,5121.337395,4455.1325,47728.414895
26,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-0.103597,0.0000,-0.103597
27,6958.5485,7013.1235,10945.0065,13714.6795,7189.9920,7961.0230,11242.6185,8134.7675,7683.203995,7555.8695,88398.832495
28,6052.2300,6256.9740,9721.7140,11346.8860,5633.8845,7277.9785,9884.5720,6988.8810,6156.448701,5684.1385,75003.707201
29,5977.9790,6565.6205,8755.5230,10318.0705,5636.3515,6897.3485,8339.5050,6107.2940,6100.771983,5423.6775,70122.141483
...,...,...,...,...,...,...,...,...,...,...,...
905,5281.5115,6134.8185,7841.7545,10667.4840,5642.5035,5374.6045,10768.8330,8660.7415,8414.212036,6638.1260,75424.589036
906,4904.9280,4894.3610,8057.6890,11070.9365,5072.9255,5006.9850,11433.4805,6868.0810,8360.900295,6015.6800,71685.966795
907,4761.7630,4077.3620,4471.8050,9917.2190,2113.0615,3039.7590,6984.1550,3780.5330,6305.686531,5292.6185,50743.962531
908,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000004,0.0000,0.000004
909,4223.2230,4282.4120,6921.5410,9772.3580,4218.3175,4465.3200,10678.7540,6437.6255,7758.440322,6008.7685,64766.759822
910,3791.8625,4144.6840,6361.5215,8327.0880,3930.1525,4132.3645,9609.5130,5470.3565,6712.627470,5529.3455,58009.515470
911,3810.2060,5413.8545,6056.9640,8446.1625,4634.7685,4193.1325,8953.3580,5309.9215,5724.663897,5154.5525,57697.583897
912,3807.7405,4169.6345,6286.4235,8719.5765,4521.5970,4028.9745,9353.7355,5713.2945,6194.665558,5001.9265,57797.568558
913,3861.6185,4518.2670,6322.8415,9153.0460,4414.6415,4372.9920,9499.8430,5743.7120,6250.658606,5557.2140,59694.834106
914,3987.5760,2775.9870,4159.3575,10221.3300,2036.9385,3133.4190,6444.0065,3638.5735,6144.192101,4746.2235,47287.603601
915,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000004,0.0000,0.000004
916,5316.9075,7235.2915,9607.8940,13415.6890,7613.2885,6752.4395,13640.2560,9229.7625,9635.449072,7043.4310,89490.408572
917,5041.7355,6290.7105,8947.7420,11637.6360,6153.8620,5884.0350,11955.4585,8411.3470,8224.462102,6894.8135,79441.802102
918,4916.0115,6564.7210,8428.0185,11428.5455,6020.2665,4966.1985,10507.4425,7956.3015,7314.389355,6456.8025,74558.697355
919,4453.7145,5243.6650,7873.2845,10895.7615,5271.6580,5093.2995,10296.6955,8504.7905,7216.366731,6169.4980,71018.733731
920,4666.6895,4741.3355,7178.5600,10733.5175,4795.1560,4755.8610,10679.9695,7056.5105,7863.615721,5800.7030,68271.918221
921,4383.0425,3021.5765,4016.9475,9814.7305,2031.7670,2987.9005,6719.3355,3839.6945,6189.458812,5416.6175,48421.070812
922,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000004,0.0000,0.000004
923,3947.8235,4080.6970,5774.7770,9906.8255,3989.1705,4214.6125,9934.7480,5904.8105,7158.817204,5860.5755,60772.857204
924,3725.6040,3999.2120,5732.1530,8948.5815,3701.2250,3935.2700,9258.0045,5327.4385,5893.877555,5936.8965,56458.262555
925,3744.0430,5078.2325,5492.4595,8723.8830,3993.6445,3752.8785,8470.3455,5180.0420,5799.633389,5436.9945,55672.156389
926,3726.8500,4130.4230,5613.6665,7997.8610,3671.4985,3705.5345,9201.4690,5945.0450,6494.586500,5941.4560,56428.390000
927,3790.6345,3970.5710,5527.7865,8106.2990,3989.5975,3929.4285,9276.6460,5059.4955,6248.572582,5849.9770,55749.008082
928,4232.9485,2625.4120,4092.1550,9474.3595,2002.1275,2913.6610,6605.8875,3366.7325,6203.389578,4888.2625,46404.935578
929,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000004,0.0000,0.000004
930,5820.2905,6904.3110,8879.2595,11975.8960,7307.3300,6089.7520,14385.0985,9009.8055,9585.756007,7198.1300,87155.629007
931,5173.8675,6014.1075,8552.3065,10397.0820,5966.4590,5027.4595,12403.1240,7219.6115,8308.462426,6240.9550,75303.434926
932,4882.6140,6311.8060,7868.2565,10207.1670,5968.4045,5247.8865,11432.6160,6811.5175,7792.973641,5766.4895,72289.731141
933,4717.7440,5449.3175,8180.1835,10750.5300,4992.1515,4953.3005,11532.1220,7935.4700,7722.827911,5981.6535,72215.300411
934,5165.9875,5433.7425,8252.6170,12209.8480,4930.4955,5424.2370,13363.2020,7662.9720,7818.277159,6587.4495,76848.828159

In [ ]:
# The rest of this notebook is just a reference and aid to allow collaborators to... 
# - save models
# - retrive and apply them without retraining. 

def save_model(model, filename):
    """
    Saves the model as a file. 
    - Keras models: saved as .json and .h5 files
    - scikit-learn models: saved as .pickle files
    """
    
    if type(model) is KerasRegressor:
        
        model_json = model.model.to_json()
        with open('{}.json'.format(filename), "w") as json_file:
            json_file.write(model_json)
        model.model.save_weights('{}.h5'.format(filename))        
    else:
        pickle_out = open('{}.pickle'.format(filename), "wb")
        pickle.dump(model, pickle_out)
        pickle_out.close()

    
# Save each SKU's best model to the local directory
for sku in list(df_dict.keys()):

    filename="SKU{}_best_model".format(sku)
    model = bm_dict[sku][1]

    save_model(model, filename)

In [ ]:
# Load pickled models
# loaded_model = pickle.load(open('SKU1_best_model.pickle', 'rb'))
# print(type(loaded_model) is RandomForestRegressor)

def load_pickled_model(path_to_model):
    loaded_model = pickle.load(open(path_to_model, 'rb'))
    
    return loaded_model

def load_keras_model(path_to_json, path_to_weights_h5):
    
    # load json and create model
    json_file = open(path_to_json, 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)

    # load weights into new model
    loaded_model.load_weights(path_to_weights_h5)
    
    # wrap Sequential obj as a KerasRegressor to allow scikit-learn compatibility
    wrapped_loaded_model = KerasRegressor(build_fn=create_MLP, epochs=400, batch_size=20, verbose=0)
    
    return wrapped_loaded_model

def load_model(filename):
    """
    Loads a given file as a model
    - .pickle files: loaded as scikit-learn models
    - .json and .h5 files: loaded together to create Keras models
    """
    
    loaded_model = None
    
    try:
        loaded_model = load_pickled_model("{}.pickle".format(filename))
        
    except FileNotFoundError:
        loaded_model = load_keras_model("{}.json".format(filename), "{}.h5".format(filename))
        
    return loaded_model
        
    
loaded_models={}
for i in range(1,11):
    model = load_model("SKU{}_best_model".format(i))
    loaded_models[i] = model

# loaded_models[9].compile(loss='mse', optimizer='adam', metrics=['mae','mse'])
# loaded_models[9].evaluate(X[9], y[9], verbose=0)

In [ ]:
# Evaluate loaded model on test data
# loaded_model.compile(loss='mse', optimizer='adam', metrics=['mae','mse'])
# score = loaded_model.evaluate(Xs, y, verbose=0)
# print("%s: %.0f"%  (loaded_model.metrics_names[1], score[1]))
# print("%s: %.1f"%  (loaded_model.metrics_names[2], score[2]/10000000))

# Remember cv is cross validation, which is set to 2 earlier. Thus, X is divided into 2 subsets for train/test process
scores=[]
model_family=[]
for sku in range(1,11):
    
    # Identify the model family
    model = loaded_models[sku]
    if isinstance(model, RandomForestRegressor):
        model_family.append('RF')
    else:
        model_family.append('MLP')

    # Obtain the cross validation score
    score = -cross_val_score(model,X[sku],y[sku],cv=cv, scoring ='mean_absolute_error').mean().round(0)
    scores.append(score)        

loaded_model_scores = pd.DataFrame({
    'CV Score':scores,
    'Family':model_family
})
loaded_model_scores.index += 1

loaded_model_scores